export { default as curry } from '@basic/curry';
export { default as curryRight } from '@basic/curryRight';
// export { default as deepFlat } from '@basic/deepFlat';
export { default as delay } from '@basic/delay';
// export { default as entries } from '@basic/entries';
export { default as filter } from '@basic/filter';
// export { default as flat } from '@basic/flat';
// export { default as flatMap } from '@basic/flatMap';
// export { default as forEach } from '@basic/forEach';
// export { default as go } from '@basic/go';
// export { default as groupBy } from '@basic/groupBy';
export { default as head } from '@basic/head';
// export { default as identity } from '@basic/identity';
// export { default as join } from '@basic/join';F
// export { default as keys } from '@basic/keys';
// export { default as last } from '@basic/last';
export { default as map } from '@basic/map';
// export { default as object } from '@basic/object';
// export { default as pipe } from '@basic/pipe';
export { default as range } from '@basic/range';
export { default as reduce } from '@basic/reduce';
// export { default as reject } from '@basic/reject';
export { default as take } from '@basic/take';
export { default as takeAll } from '@basic/takeAll';
// export { default as tap } from '@basic/tap';
// export { default as values } from '@basic/values';
// export { default as filterC } from '@concurrency/filterC';
// export { default as forEachC } from '@concurrency/forEachC';
// export { default as mapC } from '@concurrency/mapC';
// export { default as objectC } from '@concurrency/objectC';
// export { default as reduceC } from '@concurrency/reduceC';
// export { default as rejectC } from '@concurrency/rejectC';
// export { default as takeAllC } from '@concurrency/takeAllC';
export { default as takeC } from '@concurrency/takeC';
// export { default as deepFlatL } from '@lazy/deepFlatL';
// export { default as entriesL } from '@lazy/entriesL';
export { default as filterL } from '@lazy/filterL';
// export { default as flatL } from '@lazy/flatL';
// export { default as flatMapL } from '@lazy/flatMapL';
// export { default as forEachL } from '@lazy/forEachL';
// export { default as keysL } from '@lazy/keysL';
export { default as mapL } from '@lazy/mapL';
export { default as rangeL } from '@lazy/rangeL';
// export { default as rejectL } from '@lazy/rejectL';
export { default as takeL } from '@lazy/takeL';
// export { default as valuesL } from '@lazy/valuesL';