export { default as identity } from '@basic/identity';
export { default as delay } from '@basic/delay';
export { default as curry } from '@basic/curry';
export { default as curryRight } from '@basic/curryRight';
export { default as take } from '@basic/take';
export { default as takeAll } from '@basic/takeAll';
export { default as head } from '@basic/head';
export { default as last } from '@basic/last';
export { default as range } from '@basic/range';
export { default as map } from '@basic/map';
export { default as forEach } from '@basic/forEach';
export { default as filter } from '@basic/filter';
export { default as reduce } from '@basic/reduce';
export { default as go } from '@basic/go';
export { default as pipe } from '@basic/pipe';
export { default as tap } from '@basic/tap';

export { default as takeL } from '@lazy/takeL';
export { default as rangeL } from '@lazy/rangeL';
export { default as mapL } from '@lazy/mapL';
export { default as forEachL } from '@lazy/forEachL';
export { default as filterL } from '@lazy/filterL';

export { default as takeC } from '@concurrency/takeC';
export { default as takeAllC } from '@concurrency/takeAllC';
export { default as mapC } from '@concurrency/mapC';
export { default as forEachC } from '@concurrency/forEachC';
export { default as filterC } from '@concurrency/filterC';
export { default as reduceC } from '@concurrency/reduceC';